### ISSUE TITLE
Should we craft a glossary section?  If so, we will need to capture entries by section

### ISSUE THREAD

**Issue by thagerdc** [fdevaulx/blockchain-playbook-dev#25]

**Comment by kodumudi-cgi** [comment]
Glossary Section does makes sense. I think we should have one Glossary Section for the entire playbook.

Thanks

**Comment by thagerdc** [comment]
I like this version of a blockchain glossary provided by Alex Rebo
[Blockchain-Distributed-ledger-glossary.pdf](https://github.com/fdevaulx/blockchain-playbook/files/1652327/Blockchain-Distributed-ledger-glossary.pdf)
